#!/usr/bin/env bash
# Bash script that displays the subdomain and domains connected to your servers respectively

# Function to display information for a subdomain
display_subdomain_info() {
    local subdomain=$1
    local ip_address=$2
    local server_name=$3
    echo "Your subdomain $subdomain points to your $server_name server IP"
}

# Check if domain argument is provided
if [[ -z $1 ]]; then
    echo "Domain argument is mandatory"
    exit 1
fi

domain=$1
subdomain=$2

# Display information for default subdomains if subdomain argument is not provided
if [[ -z $subdomain ]]; then
    display_subdomain_info "www" "54.86.45.134" "lb-01"  # www points to lb-01 IP
    display_subdomain_info "lb-01" "54.86.45.134" "lb-01"  # lb-01 IP
    display_subdomain_info "web-01" "3.94.54.124" "web-01"  # web-01 IP
    display_subdomain_info "web-02" "18.212.186.27" "web-02"  # web-02 IP
else
    # Display information for specified subdomain
    case $subdomain in
        www)
            display_subdomain_info "www" "54.86.45.134" "lb-01"  # www points to lb-01 IP
            ;;
        lb-01)
            display_subdomain_info "lb-01" "54.86.45.134" "lb-01"  # lb-01 IP
            ;;
        web-01)
            display_subdomain_info "web-01" "3.94.54.124" "web-01"  # web-01 IP
            ;;
        web-02)
            display_subdomain_info "web-02" "18.212.186.27" "web-02"  # web-02 IP
            ;;
        *)
            echo "Invalid subdomain: $subdomain"
            ;;
    esac
fi

